version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/backend-controller'
    schedule:
      interval: 'daily'
  

  - package-ecosystem: 'maven'
    directory: '/backend-worker'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'daily'
