services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FINAL_PORT}:80
    depends_on:
      backend-worker:
        condition: service_healthy
      cheese-auth:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/api/cheese-auth/status && curl -f http://localhost/api/sandbox/status"]
      start_period: 180s
      start_interval: 5s
      interval: 1m
      timeout: 10s
      retries: 3

  backend-worker:
    image: ghcr.io/sageseekersociety/snake:${BACKEND_WORKER_TAG:-main}
    env_file: .env
    volumes:
      - type: volume
        source: backend_worker_data
        target: /app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/status"]
      start_period: 180s
      start_interval: 5s
      interval: 1m
      timeout: 10s
      retries: 3
    privileged: true

  cheese-auth:
    image: ghcr.io/sageseekersociety/cheese-auth:${CHEESE_AUTH_TAG:-main}
    env_file: .env
    volumes:
      - type: volume
        source: cheese_auth_uploads
        target: /app/uploads
    depends_on:
      cheese-auth-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/status"]
      start_period: 180s
      start_interval: 5s
      interval: 1m
      timeout: 10s
      retries: 3

  cheese-auth-database:
    image: postgres:16.2
    env_file: .env
    volumes:
      - type: volume
        source: cheese_auth_db_pg
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 180s
      start_interval: 5s
      interval: 1m
      timeout: 10s
      retries: 3
  
volumes:
  backend_worker_data:
  cheese_auth_uploads:
  cheese_auth_db_pg:
