/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.11.0). https://openapi-generator.tech Do not edit the class manually.
 */
package org.rucca.snake.controller.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface CompileApi {

    @Operation(
        tags = ["default"],
        summary = "Export latest successful source per user as ZIP",
        operationId = "compileExportLatestSourcesZipGet",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "ZIP stream",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(
                                        implementation = org.springframework.core.io.Resource::class
                                    )
                            )
                        ],
                ),
                ApiResponse(
                    responseCode = "403",
                    description = "Forbidden (not in admin whitelist)",
                ),
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/compile/export/latest-sources.zip"],
        produces = ["application/zip"],
    )
    fun compileExportLatestSourcesZipGet(): ResponseEntity<org.springframework.core.io.Resource> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
