/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.11.0). https://openapi-generator.tech Do not edit the class manually.
 */
package org.rucca.snake.controller.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.rucca.snake.controller.model.SubmitPost200ResponseDTO
import org.rucca.snake.controller.model.SubmitPost400ResponseDTO
import org.rucca.snake.controller.model.SubmitPost403ResponseDTO
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface SubmitApi {

    @Operation(
        tags =
            [
                "default",
            ],
        summary = "Submit source code",
        operationId = "submitPost",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "Submission successful",
                    content =
                        [Content(schema = Schema(implementation = SubmitPost200ResponseDTO::class))]
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad request",
                    content =
                        [Content(schema = Schema(implementation = SubmitPost400ResponseDTO::class))]
                ),
                ApiResponse(
                    responseCode = "403",
                    description = "Submission rejected",
                    content =
                        [Content(schema = Schema(implementation = SubmitPost403ResponseDTO::class))]
                )
            ]
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/submit"],
        produces = ["application/json"],
        consumes = ["multipart/form-data"]
    )
    fun submitPost(
        @Parameter(description = "Source code file")
        @Valid
        @RequestPart("src", required = false)
        src: org.springframework.web.multipart.MultipartFile?
    ): ResponseEntity<SubmitPost200ResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
