spring.application.name=snake.controller
server.port=8080

cheese-auth.jwt-secret=test-secret
cheese-auth.warn-audit-failure=true

application.worker-urls=http://localhost:8081
application.cors.allowed-origins=http://localhost:3000,http://localhost:8080


# The following configuration is only used by tests:

# Default database configuration
# If you follow README.md and use docker to setup the database, this configuration should work
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=username
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

cheese-auth.auth-server-url=${CHEESE_AUTH_SERVER_URL:http://localhost:8080}

