{
 "title": "Snake Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Job Submissions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_submissions_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Total Job Outcomes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "job_outcomes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Available Nsjail Permits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "nsjail_permits_available", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Execution E2E Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "job_processing_duration_seconds",
     "legendFormat": "P{{quantile}}"
    }
   ]
  }
 ]
}