spring.application.name=snake.worker

# Default database configuration
# If you follow README.md and use docker to setup the database, this configuration should work
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=username
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

cheese-auth.auth-server-url=http://localhost:8080
cheese-auth.jwt-secret=test-secret
cheese-auth.warn-audit-failure=true

application.compiler-path=/bin/clang++
application.compiler-parameter[0]=-O2
application.data-directory=./data

application.nsjail-path=/usr/local/src/nsjail/nsjail
#  -M o \
#  -R /lib -R /lib64/ \
#  --disable_proc \
#  --rlimit_cpu 1 \
#  --rlimit_as 300 \
#  --rlimit_nproc 0 \
#  --rlimit_fsize 0 \
#  --user 99999 --group 99999 \
application.nsjail-parameter[0]=-M
application.nsjail-parameter[1]=o
application.nsjail-parameter[2]=-R
application.nsjail-parameter[3]=/lib
application.nsjail-parameter[4]=-R
application.nsjail-parameter[5]=/lib64
application.nsjail-parameter[6]=--disable_proc
application.nsjail-parameter[7]=--rlimit_cpu
application.nsjail-parameter[8]=1
application.nsjail-parameter[9]=--rlimit_as
application.nsjail-parameter[10]=300
application.nsjail-parameter[11]=--rlimit_nproc
application.nsjail-parameter[12]=0
application.nsjail-parameter[13]=--rlimit_fsize
application.nsjail-parameter[14]=0
application.nsjail-parameter[15]=--user
application.nsjail-parameter[16]=99999
application.nsjail-parameter[17]=--group
application.nsjail-parameter[18]=99999
application.nsjail-parameter[19]=--quiet

