spring.application.name=snake.worker

# Default database configuration
# If you follow README.md and use docker to setup the database, this configuration should work
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=username
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

cheese-auth.auth-server-url=http://localhost:8080
cheese-auth.jwt-secret=test-secret
cheese-auth.warn-audit-failure=true

application.compiler-path=/bin/clang++
application.compiler-parameter[0]=-O2
application.compiler-parameter[1]=-fsanitize=address
application.data-directory=./data
