spring.application.name=snake.worker
server.port=8080

cheese-auth.jwt-secret=test-secret
cheese-auth.warn-audit-failure=true

application.compiler-path=/bin/clang++
application.compiler-parameter=-O2
application.data-directory=./data
application.cors.allowed-origins=http://localhost:3000,http://localhost:8080

application.nsjail-path=/usr/local/src/nsjail/nsjail
application.nsjail-parameter=-M,o,-R,/lib,-R,/lib64,--disable_proc,--rlimit_cpu,1,--rlimit_as,300,--rlimit_nproc,0,--rlimit_fsize,0,--user,99999,--group,99999,--quiet


# The following configuration is only used by tests:

# Default database configuration
# If you follow README.md and use docker to setup the database, this configuration should work
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=username
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

cheese-auth.auth-server-url=${CHEESE_AUTH_SERVER_URL:http://localhost:8080}

